<a href="https://colab.research.google.com/github/DGluszyk/data-science-bootcamp/blob/main/06_Uczenie_maszynowe_sklearn/03_metryki_regresja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [2]:
y_true = 100 + 20 * np.random.randn(50)
y_true

array([ 58.45467472, 121.69557034, 106.05719427, 107.99247354,
       105.88842984,  88.49545414, 109.42079463,  75.05519861,
       117.01599668, 120.3339157 , 106.84007966,  74.45872982,
        87.58936466, 141.9702203 , 108.5291851 ,  94.5370025 ,
        92.80082494,  89.10916039,  86.32346171,  87.54365543,
        93.27741222, 120.76970588,  77.89188973, 123.82196735,
        91.46097283, 103.17240867, 130.66234252, 147.1724072 ,
        85.57106127, 108.5221739 , 109.00616921, 104.08514633,
       138.81236523,  73.42512638, 124.81732351, 103.01936734,
        91.52133495,  85.65629269,  98.66041752,  81.58402975,
       110.7335457 ,  89.1542419 , 138.24484474,  86.48519809,
       108.40019649,  76.76150548,  92.31249675,  91.57786656,
        86.74473437,  67.55599076])

In [3]:
y_pred = y_true + 10 * np.random.randn(50)
y_pred

array([ 50.19682108, 123.61187305,  96.19856872,  91.30632852,
       103.95486619,  81.42226204, 123.26899165,  74.13619102,
       124.72544878, 119.66585734, 121.04798918,  77.24382359,
        97.92452341, 139.82680279,  89.25828745,  97.14317599,
        94.42199108, 103.65894535,  91.77613618, 106.37674894,
       108.60875937, 129.42329396,  80.52415344, 134.86484629,
        81.01968063,  94.58274634, 129.8087846 , 142.38988436,
       105.02191054, 112.16047361, 108.87640623, 105.84339454,
       142.93058767,  73.87728487, 120.27915569, 102.89037819,
        81.60636783,  80.95209981,  90.72865759,  79.23608229,
        98.07025284,  85.21774995, 158.07191737,  94.06010838,
       110.00001654,  78.68214677,  93.53021   ,  95.80923617,
        91.45781546,  65.01981506])

In [4]:
result = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
result.head()

       y_true      y_pred
0   58.454675   50.196821
1  121.695570  123.611873
2  106.057194   96.198569
3  107.992474   91.306329
4  105.888430  103.954866

In [5]:
result['error'] = result['y_true'] - result['y_pred']
result.head()

       y_true      y_pred      error
0   58.454675   50.196821   8.257854
1  121.695570  123.611873  -1.916303
2  106.057194   96.198569   9.858626
3  107.992474   91.306329  16.686145
4  105.888430  103.954866   1.933564

In [6]:
def plot_regression_results(y_true, y_pred):
    results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
    min = results[['y_true', 'y_pred']].min().min()
    max = results[['y_true', 'y_pred']].max().max()

    fig = go.Figure(data=[go.Scatter(x=results['y_true'], y=results['y_pred'], mode='markers'),
                    go.Scatter(x=[min, max], y=[min, max])],
                    layout=go.Layout(showlegend=False, width=800, height=500,
                                     xaxis_title='y_true',
                                     yaxis_title='y_pred',
                                     title='Regression results'))
    fig.show()
plot_regression_results(y_true, y_pred)

In [7]:
y_true = 100 + 20 * np.random.randn(1000)
y_pred = y_true + 10 * np.random.randn(1000)
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results['error'] = results['y_true'] - results['y_pred']

px.histogram(results, x='error', nbins=50, width=800)

In [8]:
def mean_absolute_error(y_true, y_pred):
    return abs(y_true - y_pred).sum() / len(y_true)

mean_absolute_error(y_true, y_pred)

np.float64(8.07819041536437)

In [9]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_true, y_pred)

8.07819041536437

In [10]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_true, y_pred)

104.12265349220185

In [11]:
def root_mean_squared_error(y_true, y_pred):
    return np.sqrt(((y_true - y_pred) ** 2).sum() / len(y_true))

root_mean_squared_error(y_true, y_pred)

np.float64(10.204050837397952)

In [12]:
np.sqrt(mean_squared_error(y_true, y_pred))

np.float64(10.204050837397952)

In [13]:
from sklearn.metrics import max_error

max_error(y_true, y_pred)

np.float64(35.70740256960842)

In [14]:
from sklearn.metrics import r2_score

r2_score(y_true, y_pred)

0.7407771713263798